#!/bin/bash

# Zcash ports start at 40000, RPC ports start at 50000.

NUMNODES=$1
if [ "$NUMNODES" = "" ]; then echo "Number of nodes expected." >&2; return 1; fi

PATH=$PATH:zcash/src

for i in $(seq 0 $((NUMNODES - 1))); do
	mkdir -p "node$i"
	touch "node$i"/zcash.conf
	zcashd -debug -regtest -datadir="node$i" -conf=zcash.conf \
	        -port=$((40000 + i)) -rpcport=$((50000 + i)) -nuparams=c2d6d0b4:1 &
done
