#!/bin/bash

# Zcash ports start at 40000, RPC ports start at 50000.

NUMNODES=$1
if [ "$NUMNODES" = "" ]; then echo "Number of nodes expected." >&2; return 1; fi

PATH=$PATH:zcash/src

mkdir -p logs
LOGFILE=logs/all.log.0
# find next unused log file name
while [ -f $LOGFILE ]; do i=$((i + 1)); LOGFILE=logs/all.log.$i; done

for i in $(seq 0 $((NUMNODES - 1))); do
	mkdir -p "node$i"
	touch "node$i"/zcash.conf
	zcashd -printtoconsole -debug -regtest -datadir="node$i" -conf=zcash.conf \
		-port=$((40000 + i)) -rpcport=$((50000 + i)) \
		| sed -e 's/^/[NODE'$i'] /' 2>&1 >> $LOGFILE &
done
